#!/bin/python3

import math
import os
import random
import re
import sys

if __name__ == '__main__':
    n = int(input())
    biNum = bin(n)[2:]
    biNumList = list(biNum)

    count = 0
    max = 0
    for i in biNumList:
        if i == '1':
            count += 1
            if count > max:
                max = count 
        else:
            count = 0

    print(max)
    
